trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
  
- script: |
    sqllocaldb create "SqlBatis" 14.0 -s  
    sqlcmd -S (localdb)\SqlBatis -E -i .\test\SqlBatis.DataMapper.Test\Scripts\MSSQL\DataBase.sql
  displayName: 'Setup LocalDB for Tests'
  
- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: test
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: MSSQL Tests
  inputs:
    command: test
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --filter Category=MSSQL'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish    
    publishTestResults: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
