trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- script: setupdb.cmd
  displayName: 'Setup LocalDB for Tests'
  
- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: test
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: MSSQL Tests
  inputs:
    command: test
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --filter Category=MSSQL'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish    
    publishTestResults: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
